apiVersion: v1
kind: Service
metadata:
  labels:
    service: web
  name: web
  namespace: jitsi
spec:
  ports:
  - name: "http"
    port: 80
    targetPort: 80
  - name: "https"
    port: 443
    targetPort: 443
  selector:
    k8s-app: jitsi
  type:
    NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jitsi
  namespace: jitsi
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - <hostname here>
    secretName: <secret name here>
  rules:
  - host: <hostname here>
    http:
      paths:
      - path: /
        backend:
          serviceName: web 
          servicePort: 80
